name: C/C++ CI

on:
  push:
#    branches: [ "main" ]
    branches:  
      - '*' 
  pull_request:
    branches: 
      - '*' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
  norminette:
    runs-on: ubuntu-lastest
    steps:
    - name: 42 Norminette
        # You may pin to the exact commit or the version.
        # uses: alexandregv/norminette-action@99553916aada3d882aaa35cd1fd51b433234749e
      uses: alexandregv/norminette-action@v3.3.53
      with:
        # Flags passed to norminette
        flags: ./src ./inc  # default is .
          
