name: C/C++ CI

on:
  push:
#    branches: [ "main" ]
    branches:  
      - '*' 
  pull_request:
    branches: 
      - '*' 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: alexandregv/norminette-action@v3.3.53
      with:
        flags: 'src/' 'inc/'  # default is .